FORMAT: 1A
HOST: http://api.xxhuzhu.com

# xxhuzhu API
Draft version of xxhuzhu APIs. These APIs will be used by xxhuzhu iOS App.

# Group Programs

##Programs [/programs]

A program is the smallest unit that a member can enroll. Once a member enrolls a program, 
the member will be resposible for taking care of members in the same program who are 
qualified for claim. The more programs a member joins, the more he/she will have to pay.

A program has a `open` status (true or false) indicating whether new members can enroll.

A program has a `mature` status (true or false) indicating whether qualified members can claim.

A program has a `matureThreshold`, once the number of qualified members reached this number,
the `mature` status shall become true.

A program has a `immatureThreshold`, once the number of qualified members goes below this number, 
the `mature` status shall become false.

A program has a `maxMaturingPeriod` indicating how many days

## Programs[/programs]
### Get the summary of all programs [GET]
+ Response 200 (application/json)

        [{
          "id": 11, // the unique id
          "name": "Lung Cancer",
          "open": true,
          "mature": false,
          "matureThreshold": 10000,
          "immatureThreshold": 5000,
          "maxMaturingPeriod": 365,
          "terms": "the terms in markdown",
          "termsVer": 1.0,
          "groups": "Recommended, Default",
          "tags": ["Cancer", "Female"]
        }, {
          "id": 12, // the unique id
          "name": "Head Cancer",
          "open": true,
          "mature": true,
          "matureThreshold": 10000,
          "immatureThreshold": 5000,
          "maxMaturingPeriod": 365,
          "terms": "the terms in markdown",
          "termsVer": 1.0,
          "groups": "Recommended, Default",
          "tags": ["Cancer", "Female"]
        }]

## Retrieve a Program[/program/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header


    + Body

            {
              "id": 11, // the unique id
              "name": "Lung Cancer",
              "open": true,
              "mature": false,
              "matureThreshold": 10000,
              "immatureThreshold": 5000,
              "maxMaturingPeriod": 365,
              "terms": "the terms in markdown",
              "termsVer": 1.0,
              "groups": "Recommended, Default",
              "tags": ["Cancer", "Female"]
            }

### Remove a Note [DELETE]
+ Response 204
