FORMAT: 1A
HOST: http://www.xxhuzhu.com

# xxhuzhu API
Draft version of xxhuzhu APIs. These APIs will be used by xxhuzhu iOS App.

#Programs

A program is the smallest unit that a member can enroll. Once a member enrolls a program, 
the member will be resposible for taking care of members in the same program who are 
qualified for claim. The more programs a member joins, the more he/she will have to pay.

A program has a `open` status (true or false) indicating whether new members can enroll.

A program has a `mature` status (true or false) indicating whether qualified members can claim.

## Programs [/programs]
### Get the summary of all programs [GET]
+ Response 200 (application/json)

        [{
          "id": 12345, // the unique id
          "name": "Lung Cancer",
          "status": "mature"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
